/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khuyenmai;

import Util.MyConvert;
import Util.MyInstance;
import khuyenmai.KhuyenMai;
import khuyenmai.KhuyenMaiDAO;
import khuyenmai.KhuyenMaiFrame;

import javax.swing.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;

/**
 * @author khanh
 */
public class ThongTinKM extends javax.swing.JFrame {

    /**
     * Creates new form ThôngTinKM
     */
    private Integer isInstance = 0;
    private Thread threadNhan;
    KhuyenMaiDAO kmDAO = new KhuyenMaiDAO();
    KhuyenMai km;
    ArrayList<KhuyenMai> listKM = new ArrayList<>();

    public ThongTinKM() {
        initComponents();
        dateNGBD.setDateFormatString("dd-MM-yyyy");
        dateNGKT.setDateFormatString("dd-MM-yyyy");
    }

    @Override
    public void dispose() {
        synchronized (threadNhan) {
            threadNhan.notify();
        }
        super.dispose();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTTKM = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lba12 = new javax.swing.JLabel();
        txtMAKM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTL = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dateNGBD = new com.toedter.calendar.JDateChooser();
        btnL = new javax.swing.JButton();
        btnT = new javax.swing.JButton();
        dateNGKT = new com.toedter.calendar.JDateChooser();
        txtTENKM = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelTTKM.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("THÔNG TIN KHUYẾN MÃI");

        jLabel2.setBackground(new java.awt.Color(153, 153, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/Khuyenmai2.png"))); // NOI18N

        lba12.setBackground(new java.awt.Color(255, 255, 255));
        lba12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lba12.setText("Mã khuyến mãi");

        txtMAKM.setToolTipText("Mã khách hàng");
        txtMAKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMAKMActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Tên khuyến mãi");

        txtMT.setToolTipText("Mã khách hàng");
        txtMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMTActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Mô tả");

        txtTL.setToolTipText("Mã khách hàng");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Tỉ lệ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Ngày bắt đầu");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Ngày kết thúc");

        btnL.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnL.setText("Chấp nhận");
        btnL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLActionPerformed(evt);
            }
        });

        btnT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnT.setText("Thoát");
        btnT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTActionPerformed(evt);
            }
        });

        txtTENKM.setToolTipText("Mã khách hàng");
        txtTENKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTENKMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTTKMLayout = new javax.swing.GroupLayout(jPanelTTKM);
        jPanelTTKM.setLayout(jPanelTTKMLayout);
        jPanelTTKMLayout.setHorizontalGroup(
                jPanelTTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTTKMLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelTTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelTTKMLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(jPanelTTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lba12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(txtMAKM))
                                .addGap(26, 26, 26)
                                .addGroup(jPanelTTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelTTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanelTTKMLayout.createSequentialGroup()
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtTENKM, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanelTTKMLayout.createSequentialGroup()
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtMT, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanelTTKMLayout.createSequentialGroup()
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtTL, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanelTTKMLayout.createSequentialGroup()
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(dateNGBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelTTKMLayout.createSequentialGroup()
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(dateNGKT, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanelTTKMLayout.createSequentialGroup()
                                                .addGap(199, 199, 199)
                                                .addComponent(btnL, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(46, 46, 46)
                                                .addComponent(btnT, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTTKMLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(227, 227, 227))
        );
        jPanelTTKMLayout.setVerticalGroup(
                jPanelTTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTTKMLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelTTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelTTKMLayout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelTTKMLayout.createSequentialGroup()
                                                .addGap(95, 95, 95)
                                                .addGroup(jPanelTTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtTENKM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanelTTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtMT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanelTTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtTL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(8, 8, 8)
                                .addGroup(jPanelTTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(dateNGBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanelTTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lba12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelTTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelTTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtMAKM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(dateNGKT, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                                .addGap(95, 95, 95)
                                .addGroup(jPanelTTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnL, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnT, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelTTKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelTTKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creatkm() {
        km = new KhuyenMai();
        km.setMAKM(txtMAKM.getText());
        km.setTENKM(txtTENKM.getText());
        km.setMOTA(txtMT.getText());
        km.setTILE(txtTL.getText().isEmpty() ? null : MyConvert.parseStringToFloat(txtTL.getText()));

        km.setNGBD(dateNGBD.getDate());
        km.setNGKT(dateNGKT.getDate());

    }

    private void paint() {

        try {
            txtMAKM.setText(km.getMAKM());
            txtMAKM.setText(km.getTENKM());
            txtMT.setText(km.getMOTA());
            txtTL.setText(MyConvert.parseFloatToString(km.getTILE()));
            dateNGBD.setDate(km.getNGBD());
            dateNGKT.setDate(km.getNGKT());
        } catch (IllegalArgumentException ex) {
            System.out.println("ngayKM null" + ex.toString());
        }


    }

    private void btnLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLActionPerformed
        // TODO add your handling code here:

        creatkm();

        switch (isInstance) {
            case MyInstance.IS_ADD: {

                kmDAO.insert(km);
            }
            break;
            case MyInstance.IS_EDIT: {

                kmDAO.update(km);
            }
            break;


            case MyInstance.IS_FIND: {

                listKM = kmDAO.queryByKM(km);
            }
            break;

        }
        synchronized (threadNhan) {
            threadNhan.notify();
        }
        dispose();


    }//GEN-LAST:event_btnLActionPerformed

    public ArrayList<KhuyenMai> getListKM() {
        return listKM;
    }


    public void setThem(Thread a) {
        isInstance = MyInstance.IS_ADD;
        threadNhan = a;
    }


    public void setXoa(Thread a) {
        isInstance = MyInstance.IS_REMOVE;
        threadNhan = a;
    }


    public void setSua(Thread a, KhuyenMai KhuyenMai) {
        isInstance = MyInstance.IS_EDIT;
        threadNhan = a;
        km = KhuyenMai;
        if (KhuyenMai != null)
            paint();
    }


    public void setTimKiemNC(Thread a) {
        isInstance = MyInstance.IS_FIND;
        threadNhan = a;
    }

    private void btnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTActionPerformed
        // TODO add your handling code here:
        synchronized (threadNhan) {
            threadNhan.notify();
        }
        dispose();
    }//GEN-LAST:event_btnTActionPerformed

    private void txtMAKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMAKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMAKMActionPerformed

    private void txtMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMTActionPerformed

    private void txtTENKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTENKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTENKMActionPerformed


    /**
     * @param args the command line arguments
     */
    /*  public static void main(String args[]) {
     *//* Set the Nimbus look and feel *//*


     *//* Create and display the form *//*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinKM().setVisible(true);
            }
        });
    }
*/
    public static void main(String[] args) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnL;
    private javax.swing.JButton btnT;
    private com.toedter.calendar.JDateChooser dateNGBD;
    private com.toedter.calendar.JDateChooser dateNGKT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelTTKM;
    private javax.swing.JLabel lba12;
    private javax.swing.JTextField txtMAKM;
    private javax.swing.JTextField txtMT;
    private javax.swing.JTextField txtTENKM;
    private javax.swing.JTextField txtTL;
    // End of variables declaration//GEN-END:variables
}
