/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phong;

import Util.MyConvert;
import Util.MyInstance;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;

/**
 * @author khanh
 */
public class ThongTinDSP extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinDSP
     */
    private Integer isInstance = 0;
    private Thread threadNhan;
    private DanhSachPhongDAO DSPDAO = new DanhSachPhongDAO();
    private DanhSachPhong dsp= new DanhSachPhong();
    private Phong p= new Phong();
    private PhongDAO PDAO = new PhongDAO();
    private ArrayList<Phong> listPhong = new ArrayList<>();

    public ThongTinDSP() {
        setIconImage(Toolkit.getDefaultToolkit().createImage(this.getClass().getResource("/drawable/logo.png")));
        initComponents();
        txtDG.setEnabled(false);
        txtSN.setEnabled(false);

    }

    @Override
    public void dispose() {
        synchronized (threadNhan) {
            threadNhan.notify();
        }
        super.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTTDSP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelIMG = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDG = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtGC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnL = new javax.swing.JButton();
        btnT = new javax.swing.JButton();
        txtSN = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelTTDSP.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("THÔNG TIN PHÒNG");

        jLabelIMG.setBackground(new java.awt.Color(153, 153, 0));
        jLabelIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/TTP.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Loại phòng");

        txtDG.setToolTipText("Mã khách hàng");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Đơn giá ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Số người");

        txtGC.setToolTipText("Mã khách hàng");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Ghi chú");

        btnL.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnL.setText("Chấp nhận");
        btnL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLActionPerformed(evt);
            }
        });

        btnT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnT.setText("Thoát");
        btnT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTActionPerformed(evt);
            }
        });

        txtSN.setToolTipText("Mã khách hàng");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phòng đơn", "Phòng đôi", "Phòng VIP" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Tình trạng");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sử dụng", "Bảo trì" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTTDSPLayout = new javax.swing.GroupLayout(jPanelTTDSP);
        jPanelTTDSP.setLayout(jPanelTTDSPLayout);
        jPanelTTDSPLayout.setHorizontalGroup(
            jPanelTTDSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTTDSPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTTDSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTTDSPLayout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTTDSPLayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(jPanelTTDSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTTDSPLayout.createSequentialGroup()
                                .addComponent(jLabelIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTTDSPLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(171, 171, 171)))))
                .addGroup(jPanelTTDSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTTDSPLayout.createSequentialGroup()
                        .addGroup(jPanelTTDSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTTDSPLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanelTTDSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTTDSPLayout.createSequentialGroup()
                                        .addGroup(jPanelTTDSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTTDSPLayout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))
                                            .addGroup(jPanelTTDSPLayout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)))
                                        .addGroup(jPanelTTDSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtSN, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                            .addComponent(txtDG)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTTDSPLayout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtGC, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelTTDSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanelTTDSPLayout.createSequentialGroup()
                                    .addGap(199, 199, 199)
                                    .addComponent(btnL, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(46, 46, 46)
                                    .addComponent(btnT, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelTTDSPLayout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanelTTDSPLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelTTDSPLayout.setVerticalGroup(
            jPanelTTDSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTTDSPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTTDSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTTDSPLayout.createSequentialGroup()
                        .addGroup(jPanelTTDSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDG, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanelTTDSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtSN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelIMG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTTDSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTTDSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelTTDSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTTDSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtGC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanelTTDSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnL, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnT, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTTDSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTTDSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creat() {
        Integer tempIndex =0;
        tempIndex= jComboBox1.getSelectedIndex();

        switch (tempIndex) {
            case 0:
                dsp.setTENLOAIPH("phong don");
                break;
            case 1:
                dsp.setTENLOAIPH("phong doi");
                break;
            case 2:
                dsp.setTENLOAIPH("phong vip");
                break;
        }

        dsp=DSPDAO.queryDSPbyTLP(dsp.getTENLOAIPH());

        p.setMALOAIPH(dsp.getMALOAIPH());

        tempIndex= jComboBox2.getSelectedIndex();

        switch (tempIndex) {
            case 0:
                p.setTINHTRANG("sudung");
                break;
            case 1:
                p.setTINHTRANG("baotri");
                break;
        }
        dsp.setSONGUOI(MyConvert.parseStringToInt(txtSN.getText()));
        dsp.setDONGIA(MyConvert.parseStringToInt(txtDG.getText()));
        p.setGHICHU(txtGC.getText());

    }
public ArrayList<Phong> getListPhong()
{
    return listPhong;
}
    private void paint() {
        String tempStr = dsp.getTENLOAIPH();
        Integer tempIndex = 0;
        switch (tempStr) {
            case "phong don":
                tempIndex = 0;
                break;
            case "phong doi":
                tempIndex = 1;
                break;
            case "phong vip":
                tempIndex = 2;
                break;
        }
        jComboBox1.setSelectedIndex(tempIndex);
        tempStr = p.getTINHTRANG();
        tempIndex = 1;
        switch (tempStr) {
            case "sudung":
                tempIndex = 0;
                break;
            case "baotri":
                tempIndex = 1;
                break;
        }
        jComboBox2.setSelectedIndex(tempIndex);
        txtSN.setText(MyConvert.parseIntToString(dsp.getSONGUOI()));
        txtDG.setText(MyConvert.parseIntToString(dsp.getDONGIA()));
        txtGC.setText(p.getGHICHU());
    }

    private void btnLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLActionPerformed
        // TODO add your handling code here:

        creat();

        switch (isInstance) {
            case MyInstance.IS_ADD: {
                PDAO.insert(p);

            }
            break;
            case MyInstance.IS_REMOVE: {
                PDAO.delete(p);
            }
            break;
            case MyInstance.IS_EDIT: {

                PDAO.update(p);
            }
            break;
            case MyInstance.IS_FIND: {
                listPhong=PDAO.queryByP(p);
            }
            break;

        }

        dispose();


    }//GEN-LAST:event_btnLActionPerformed


    public void setThem(Thread a) {
        isInstance = MyInstance.IS_ADD;
        threadNhan = a;
        dsp=DSPDAO.queryDSPbyTLP("phong don");
        txtDG.setText(MyConvert.parseIntToString(dsp.getDONGIA()));
        txtSN.setText(MyConvert.parseIntToString(dsp.getSONGUOI()));

    }


    public void setXoa(Thread a) {
        isInstance = MyInstance.IS_REMOVE;
        threadNhan = a;
    }


    public void setSua(Thread a, Phong phong, DanhSachPhong danhSachPhong) {
        isInstance = MyInstance.IS_EDIT;
        System.out.println("phong:"+phong.toString());
        System.out.println("danhsachphong:"+danhSachPhong.toString());
        threadNhan = a;
        p = phong;
        dsp = danhSachPhong;
        if (danhSachPhong != null)
            paint();
    }


    public void setTimKiemNC(Thread a) {
        isInstance = MyInstance.IS_FIND;
        threadNhan = a;
    }

    private void btnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_btnTActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        Integer tempIndex =0;
        tempIndex= jComboBox1.getSelectedIndex();

        switch (tempIndex) {
            case 0:
                dsp.setTENLOAIPH("phong don");
                break;
            case 1:
                dsp.setTENLOAIPH("phong doi");
                break;
            case 2:
                dsp.setTENLOAIPH("phong vip");
                break;
        }
        dsp=DSPDAO.queryDSPbyTLP(dsp.getTENLOAIPH());

        txtDG.setText(MyConvert.parseIntToString(dsp.getDONGIA()));
        txtSN.setText(MyConvert.parseIntToString(dsp.getSONGUOI()));
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnL;
    private javax.swing.JButton btnT;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelIMG;
    private javax.swing.JPanel jPanelTTDSP;
    private javax.swing.JTextField txtDG;
    private javax.swing.JTextField txtGC;
    private javax.swing.JTextField txtSN;
    // End of variables declaration//GEN-END:variables
}
